### PR TITLE
Fix Autolinking for React Native 0.69

### PR DESCRIPTION
**Pull request by Naturalclar**
Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [ ] Are the files formatted correctly?
* [ ] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description
Moved podspec location to root directory of project as it is required for autolinking to work in react-native/cli v8
Also removed podspecPath from react-native.config as the parameter is deprecated, making autolink to fail

https://github.com/react-native-community/cli/pull/1537

A few sentences describing the overall goals of the pull request.

## Related PRs or issues

List related PRs and other issues.
#979 

## Misc

Add what's missing, notes on what you tested, additional thoughts or questions.

### CODE REVIEW

**Review by MatkovIvan — COMMENTED** [review]
I'm not sure that it will work with previous versions, so it's just TODO for reviewers: we must test it not only with 0.69

**Review by Zestpond — APPROVED** [review]

**Comment by sunchanras** [comment]
Any good news to update on this issue ?

**Comment by DmitriyKirakosyan** [comment]
Hi @sunchanras , I'm currently testing it with different RN version. I confirm it works with RN 0.69 and it also looks working for pervious versions. I will merge it as soon as I'm sure it doesn't break anything.

**Comment by sunchanras** [comment]
@DmitriyKirakosyan Nice. Thank you.

**Comment by DmitriyKirakosyan** [comment]
I've recreated this in #981, with a couple of tweaks. I'm closing it. Please follow the progress in #981.

**Pull request closed without merging**
