### PR TITLE
Moving from .framework to .xcframework

### PR DESCRIPTION
**Pull request by stephenkopylov**
The main goal is ability to run projects using this library on Simulator on M1 devices

Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description
Now build-fat-framework.sh creates .xcframework with separated .frameworks for iphoneos and iphonesimulator.

## Related PRs or issues
https://github.com/microsoft/appcenter-sdk-react-native/issues/895

## Misc
I had to bump podspecs version 4.0.2 -> 4.0.3 to make local pod installation works

### CODE REVIEW

**Comment by stephenkopylov** [comment]
Unfortunately can't see why Azure's CI build failed

**Comment by russelarms** [comment]
Hey @stephenkopylov! Thank you for the contribution, we really appreciate it! 
The CI fails when run from an external repository, that's why I'm going to merge this branch into an inner feature-branch.
I'll do some additional tests on mac with arm64 and after that merge it into the develop branch.

**Comment by stephenkopylov** [comment]
Thank you @russelarms!

**Pull request merged**
