### PR TITLE
Allow builds with React added via pods

### PR DESCRIPTION
**Pull request by jpstrikesback**
Projects that add React via CocoaPods have a difficult time using AppCenter pods as the header search paths need updated manually on any `pod install` in our experience. This is compounded when using AppCenter to build.

This allows us to build AppCenter packages to build on Appcenter...it's so meta I can hardly take it. 😀 

Not sure if recursive is the best way but it works for us and just wanted to leave it here for discussion or merging if it looks good.

### CODE REVIEW

**Comment by dhei** [comment]
Hey @jpstrikesback,

Sorry for the delay of response. This looks like a nice improvement. Can you please resolve the merge conflict? Thanks.

**Comment by jpstrikesback** [comment]
Hey @dhei, thanks, we actually hit more issues with non-modular headers (`Xcode build error: include of non-modular header inside framework module`) in the AppCenter build process, but we were able to resolve them without forking & this patch (this would maybe have worked but then the shared framework (iirc) uses non-modular headers apparently and so it wouldn't build on AppCenter even though it would build locally 9/10 times, interestingly the first being the failed build, and AppCenter cleans the env of course after each...). Rather we removed the frameworks react-native link added, and used the shiny new ability to link to the node_modules folder for the podspec:

```ruby
  # Pods for AppCenter
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes/ios'
  pod 'appcenter-push', path: '../node_modules/appcenter-push/ios'
```
Then in the Podfile we liberally added some things in a post_install hook (which likely need a bit of a haircut but it let it build):

```ruby
      # Make AppCenter work...
      if target.pod_name.include? 'appcenter'
        target.native_target.build_configurations.each do |config|
          # Frameworks
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/**'
          # Libraries
          config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['LIBRARY_SEARCH_PATHS'] << '${PODS_CONFIGURATION_BUILD_DIR}/AppCenter/**'
          # Headers
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          config.build_settings['HEADER_SEARCH_PATHS'] << '${PODS_ROOT}/Headers/**'
          # Must allow non-modular header inside frameworks
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
```

**Comment by jpstrikesback** [comment]
FYI, this process should work for ExpoKit users

**Comment by guperrot** [comment]
We would need the conflicts to be resolved before looking at it in details.

**Comment by guperrot** [comment]
This PR looks abandoned and has stale files. Feel free to reopen if you have any update.

**Pull request closed without merging**
